// Generated by ts-gen. Do not edit.

#[allow(dead_code)]
use ::web_sys::Event;
#[allow(dead_code)]
use ::web_sys::Headers;
#[allow(dead_code)]
use ::web_sys::ReadableStream;
#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Event , extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type ExtendableEvent;
    #[doc = " The **`ExtendableEvent.waitUntil()`** method tells the event dispatcher that work is ongoing."]
    #[doc = ""]
    #[doc = " [MDN Reference](https://developer.mozilla.org/docs/Web/API/ExtendableEvent/waitUntil)"]
    #[wasm_bindgen(method, js_name = "waitUntil")]
    pub fn wait_until(this: &ExtendableEvent, promise: &Promise);
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type EmailSendResult;
    #[doc = " The Email Message ID"]
    #[wasm_bindgen(method, getter, js_name = "messageId")]
    pub fn message_id(this: &EmailSendResult) -> String;
    #[doc = " The Email Message ID"]
    #[wasm_bindgen(method, getter, js_name = "messageId")]
    pub fn message_id_js_string(this: &EmailSendResult) -> JsString;
    #[wasm_bindgen(method, setter, js_name = "messageId")]
    pub fn set_message_id<S: ::wasm_bindgen::JsStringLike>(this: &EmailSendResult, val: S);
}
impl EmailSendResult {
    #[doc = " * `message_id` - The Email Message ID"]
    pub fn new<S: ::wasm_bindgen::JsStringLike>(message_id: S) -> EmailSendResult {
        let inner: EmailSendResult = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_message_id(message_id);
        inner
    }
}
#[wasm_bindgen(module = "cloudflare:email", experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type EmailMessage;
    #[wasm_bindgen(constructor, catch)]
    pub fn new<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        S3: ::wasm_bindgen::JsStringLike,
    >(
        from: S,
        to: S2,
        raw: S3,
    ) -> Result<EmailMessage, Error>;
    #[wasm_bindgen(constructor, catch, js_name = "EmailMessage")]
    pub fn new_with_readable_stream<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        from: S,
        to: S2,
        raw: &ReadableStream,
    ) -> Result<EmailMessage, Error>;
    #[doc = " Envelope From attribute of the email message."]
    #[wasm_bindgen(method, getter)]
    pub fn from(this: &EmailMessage) -> String;
    #[doc = " Envelope From attribute of the email message."]
    #[wasm_bindgen(method, getter, js_name = "from")]
    pub fn from_js_string(this: &EmailMessage) -> JsString;
    #[doc = " Envelope To attribute of the email message."]
    #[wasm_bindgen(method, getter)]
    pub fn to(this: &EmailMessage) -> String;
    #[doc = " Envelope To attribute of the email message."]
    #[wasm_bindgen(method, getter, js_name = "to")]
    pub fn to_js_string(this: &EmailMessage) -> JsString;
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = EmailMessage , extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type ForwardableEmailMessage;
    #[doc = " Stream of the email message content."]
    #[wasm_bindgen(method, getter)]
    pub fn raw(this: &ForwardableEmailMessage) -> ReadableStream;
    #[doc = " An [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers)."]
    #[wasm_bindgen(method, getter)]
    pub fn headers(this: &ForwardableEmailMessage) -> Headers;
    #[doc = " Size of the email message content."]
    #[wasm_bindgen(method, getter, js_name = "rawSize")]
    pub fn raw_size(this: &ForwardableEmailMessage) -> f64;
    #[doc = " Reject this email message by returning a permanent SMTP error back to the connecting client including the given reason."]
    #[doc = ""]
    #[doc = " * `reason` - The reject reason."]
    #[doc = ""]
    #[doc = " Returns: void"]
    #[wasm_bindgen(method, js_name = "setReject")]
    pub fn set_reject<S: ::wasm_bindgen::JsStringLike>(this: &ForwardableEmailMessage, reason: S);
    #[doc = " Forward this email message to a verified destination address of the account."]
    #[doc = ""]
    #[doc = " * `rcptTo` - Verified destination address."]
    #[doc = " * `headers` - A [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers)."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves when the email message is forwarded."]
    #[wasm_bindgen(method, catch)]
    pub async fn forward<S: ::wasm_bindgen::JsStringLike>(
        this: &ForwardableEmailMessage,
        rcpt_to: S,
    ) -> Result<EmailSendResult, Error>;
    #[doc = " Forward this email message to a verified destination address of the account."]
    #[doc = ""]
    #[doc = " * `rcptTo` - Verified destination address."]
    #[doc = " * `headers` - A [Headers object](https://developer.mozilla.org/en-US/docs/Web/API/Headers)."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves when the email message is forwarded."]
    #[wasm_bindgen(method, catch, js_name = "forward")]
    pub async fn forward_with_headers<S: ::wasm_bindgen::JsStringLike>(
        this: &ForwardableEmailMessage,
        rcpt_to: S,
        headers: &Headers,
    ) -> Result<EmailSendResult, Error>;
    #[doc = " Reply to the sender of this email message with a new EmailMessage object."]
    #[doc = ""]
    #[doc = " * `message` - The reply message."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves when the email message is replied."]
    #[wasm_bindgen(method, catch)]
    pub async fn reply(
        this: &ForwardableEmailMessage,
        message: &EmailMessage,
    ) -> Result<EmailSendResult, Error>;
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type EmailAttachment;
    #[wasm_bindgen(method, getter)]
    pub fn disposition(this: &EmailAttachment) -> DispositionKind;
    #[wasm_bindgen(method, setter)]
    pub fn set_disposition<S: ::wasm_bindgen::JsStringLike>(this: &EmailAttachment, val: S);
    #[wasm_bindgen(method, getter, js_name = "contentId")]
    pub fn content_id(this: &EmailAttachment) -> Option<String>;
    #[wasm_bindgen(method, getter, js_name = "contentId")]
    pub fn content_id_js_string(this: &EmailAttachment) -> Option<JsString>;
    #[wasm_bindgen(method, setter, js_name = "contentId")]
    pub fn set_content_id<S: ::wasm_bindgen::JsStringLike>(this: &EmailAttachment, val: S);
    #[wasm_bindgen(method, getter)]
    pub fn filename(this: &EmailAttachment) -> String;
    #[wasm_bindgen(method, getter, js_name = "filename")]
    pub fn filename_js_string(this: &EmailAttachment) -> JsString;
    #[wasm_bindgen(method, setter)]
    pub fn set_filename<S: ::wasm_bindgen::JsStringLike>(this: &EmailAttachment, val: S);
    #[wasm_bindgen(method, getter, js_name = "type")]
    pub fn type_(this: &EmailAttachment) -> String;
    #[wasm_bindgen(method, getter, js_name = "type")]
    pub fn type__js_string(this: &EmailAttachment) -> JsString;
    #[wasm_bindgen(method, setter)]
    pub fn set_type<S: ::wasm_bindgen::JsStringLike>(this: &EmailAttachment, val: S);
    #[wasm_bindgen(method, getter)]
    pub fn content(this: &EmailAttachment) -> ContentKind;
    #[wasm_bindgen(method, setter)]
    pub fn set_content<S: ::wasm_bindgen::JsStringLike>(this: &EmailAttachment, val: S);
    #[wasm_bindgen(method, setter, js_name = "content")]
    pub fn set_content_with_array_buffer(this: &EmailAttachment, val: &ArrayBuffer);
    #[wasm_bindgen(method, setter, js_name = "content")]
    pub fn set_content_with_typed_array<T: ::js_sys::TypedArray>(this: &EmailAttachment, val: &T);
}
impl EmailAttachment {
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"inline\"`"]
    pub fn new_inline<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        S3: ::wasm_bindgen::JsStringLike,
        S4: ::wasm_bindgen::JsStringLike,
    >(
        content_id: S,
        filename: S2,
        r#type: S3,
        content: S4,
    ) -> EmailAttachment {
        let inner: EmailAttachment = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_disposition("inline");
        inner.set_content_id(content_id);
        inner.set_filename(filename);
        inner.set_type(r#type);
        inner.set_content(content);
        inner
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"inline\"`"]
    pub fn new_inline_with_array_buffer<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        S3: ::wasm_bindgen::JsStringLike,
    >(
        content_id: S,
        filename: S2,
        r#type: S3,
        content: &ArrayBuffer,
    ) -> EmailAttachment {
        let inner: EmailAttachment = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_disposition("inline");
        inner.set_content_id(content_id);
        inner.set_filename(filename);
        inner.set_type(r#type);
        inner.set_content_with_array_buffer(content);
        inner
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"inline\"`"]
    pub fn new_inline_with_typed_array<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        S3: ::wasm_bindgen::JsStringLike,
        T: ::js_sys::TypedArray,
    >(
        content_id: S,
        filename: S2,
        r#type: S3,
        content: &T,
    ) -> EmailAttachment
    where
        for<'__wbg> &'__wbg T: ::wasm_bindgen::convert::IntoWasmAbi,
    {
        let inner: EmailAttachment = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_disposition("inline");
        inner.set_content_id(content_id);
        inner.set_filename(filename);
        inner.set_type(r#type);
        inner.set_content_with_typed_array(content);
        inner
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"attachment\"`"]
    pub fn new_attachment<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        S3: ::wasm_bindgen::JsStringLike,
    >(
        filename: S,
        r#type: S2,
        content: S3,
    ) -> EmailAttachment {
        Self::builder_attachment(filename, r#type, content).build()
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"attachment\"`"]
    pub fn new_attachment_with_array_buffer<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        filename: S,
        r#type: S2,
        content: &ArrayBuffer,
    ) -> EmailAttachment {
        Self::builder_attachment_with_array_buffer(filename, r#type, content).build()
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"attachment\"`"]
    pub fn new_attachment_with_typed_array<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        T: ::js_sys::TypedArray,
    >(
        filename: S,
        r#type: S2,
        content: &T,
    ) -> EmailAttachment
    where
        for<'__wbg> &'__wbg T: ::wasm_bindgen::convert::IntoWasmAbi,
    {
        Self::builder_attachment_with_typed_array(filename, r#type, content).build()
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"attachment\"`"]
    pub fn builder_attachment<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        S3: ::wasm_bindgen::JsStringLike,
    >(
        filename: S,
        r#type: S2,
        content: S3,
    ) -> EmailAttachmentBuilder {
        let inner: EmailAttachment = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_disposition("attachment");
        inner.set_filename(filename);
        inner.set_type(r#type);
        inner.set_content(content);
        EmailAttachmentBuilder { inner }
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"attachment\"`"]
    pub fn builder_attachment_with_array_buffer<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        filename: S,
        r#type: S2,
        content: &ArrayBuffer,
    ) -> EmailAttachmentBuilder {
        let inner: EmailAttachment = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_disposition("attachment");
        inner.set_filename(filename);
        inner.set_type(r#type);
        inner.set_content_with_array_buffer(content);
        EmailAttachmentBuilder { inner }
    }
    #[doc = " ## Inlined fields"]
    #[doc = ""]
    #[doc = " * `disposition: \"attachment\"`"]
    pub fn builder_attachment_with_typed_array<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        T: ::js_sys::TypedArray,
    >(
        filename: S,
        r#type: S2,
        content: &T,
    ) -> EmailAttachmentBuilder
    where
        for<'__wbg> &'__wbg T: ::wasm_bindgen::convert::IntoWasmAbi,
    {
        let inner: EmailAttachment = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_disposition("attachment");
        inner.set_filename(filename);
        inner.set_type(r#type);
        inner.set_content_with_typed_array(content);
        EmailAttachmentBuilder { inner }
    }
}
pub struct EmailAttachmentBuilder {
    inner: EmailAttachment,
}
impl EmailAttachmentBuilder {
    pub fn content_id<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_content_id(val);
        self
    }
    pub fn build(self) -> EmailAttachment {
        self.inner
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type EmailAddress;
    #[wasm_bindgen(method, getter)]
    pub fn name(this: &EmailAddress) -> String;
    #[wasm_bindgen(method, getter, js_name = "name")]
    pub fn name_js_string(this: &EmailAddress) -> JsString;
    #[wasm_bindgen(method, setter)]
    pub fn set_name<S: ::wasm_bindgen::JsStringLike>(this: &EmailAddress, val: S);
    #[wasm_bindgen(method, getter)]
    pub fn email(this: &EmailAddress) -> String;
    #[wasm_bindgen(method, getter, js_name = "email")]
    pub fn email_js_string(this: &EmailAddress) -> JsString;
    #[wasm_bindgen(method, setter)]
    pub fn set_email<S: ::wasm_bindgen::JsStringLike>(this: &EmailAddress, val: S);
}
impl EmailAddress {
    pub fn new<S: ::wasm_bindgen::JsStringLike, S2: ::wasm_bindgen::JsStringLike>(
        name: S,
        email: S2,
    ) -> EmailAddress {
        let inner: EmailAddress = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_name(name);
        inner.set_email(email);
        inner
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type SendEmail;
    #[wasm_bindgen(method, catch)]
    pub async fn send(this: &SendEmail, message: &EmailMessage) -> Result<EmailSendResult, Error>;
    #[wasm_bindgen(method, catch, js_name = "send")]
    pub async fn send_with_builder(
        this: &SendEmail,
        builder: &SendEmailBuilder,
    ) -> Result<EmailSendResult, Error>;
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type SendEmailBuilder;
    #[wasm_bindgen(method, getter)]
    pub fn from(this: &SendEmailBuilder) -> FromKind;
    #[wasm_bindgen(method, setter)]
    pub fn set_from<S: ::wasm_bindgen::JsStringLike>(this: &SendEmailBuilder, val: S);
    #[wasm_bindgen(method, setter, js_name = "from")]
    pub fn set_from_with_email_address(this: &SendEmailBuilder, val: &EmailAddress);
    #[wasm_bindgen(method, getter)]
    pub fn to(this: &SendEmailBuilder) -> ToKind;
    #[wasm_bindgen(method, setter)]
    pub fn set_to<S: ::wasm_bindgen::JsStringLike>(this: &SendEmailBuilder, val: S);
    #[wasm_bindgen(method, setter, slice_to_array, js_name = "to")]
    pub fn set_to_with_slice(this: &SendEmailBuilder, val: &[String]);
    #[wasm_bindgen(method, getter)]
    pub fn subject(this: &SendEmailBuilder) -> String;
    #[wasm_bindgen(method, getter, js_name = "subject")]
    pub fn subject_js_string(this: &SendEmailBuilder) -> JsString;
    #[wasm_bindgen(method, setter)]
    pub fn set_subject<S: ::wasm_bindgen::JsStringLike>(this: &SendEmailBuilder, val: S);
    #[wasm_bindgen(method, getter, js_name = "replyTo")]
    pub fn reply_to(this: &SendEmailBuilder) -> Option<FromKind>;
    #[wasm_bindgen(method, setter, js_name = "replyTo")]
    pub fn set_reply_to<S: ::wasm_bindgen::JsStringLike>(this: &SendEmailBuilder, val: S);
    #[wasm_bindgen(method, setter, js_name = "replyTo")]
    pub fn set_reply_to_with_email_address(this: &SendEmailBuilder, val: &EmailAddress);
    #[wasm_bindgen(method, getter)]
    pub fn cc(this: &SendEmailBuilder) -> Option<ToKind>;
    #[wasm_bindgen(method, setter)]
    pub fn set_cc<S: ::wasm_bindgen::JsStringLike>(this: &SendEmailBuilder, val: S);
    #[wasm_bindgen(method, setter, slice_to_array, js_name = "cc")]
    pub fn set_cc_with_slice(this: &SendEmailBuilder, val: &[String]);
    #[wasm_bindgen(method, getter)]
    pub fn bcc(this: &SendEmailBuilder) -> Option<ToKind>;
    #[wasm_bindgen(method, setter)]
    pub fn set_bcc<S: ::wasm_bindgen::JsStringLike>(this: &SendEmailBuilder, val: S);
    #[wasm_bindgen(method, setter, slice_to_array, js_name = "bcc")]
    pub fn set_bcc_with_slice(this: &SendEmailBuilder, val: &[String]);
    #[wasm_bindgen(method, getter)]
    pub fn headers(this: &SendEmailBuilder) -> Option<Object<JsString>>;
    #[wasm_bindgen(method, setter)]
    pub fn set_headers(this: &SendEmailBuilder, val: &Object<JsString>);
    #[wasm_bindgen(method, getter)]
    pub fn text(this: &SendEmailBuilder) -> Option<String>;
    #[wasm_bindgen(method, getter, js_name = "text")]
    pub fn text_js_string(this: &SendEmailBuilder) -> Option<JsString>;
    #[wasm_bindgen(method, setter)]
    pub fn set_text<S: ::wasm_bindgen::JsStringLike>(this: &SendEmailBuilder, val: S);
    #[wasm_bindgen(method, getter)]
    pub fn html(this: &SendEmailBuilder) -> Option<String>;
    #[wasm_bindgen(method, getter, js_name = "html")]
    pub fn html_js_string(this: &SendEmailBuilder) -> Option<JsString>;
    #[wasm_bindgen(method, setter)]
    pub fn set_html<S: ::wasm_bindgen::JsStringLike>(this: &SendEmailBuilder, val: S);
    #[wasm_bindgen(method, getter)]
    pub fn attachments(this: &SendEmailBuilder) -> Option<Vec<EmailAttachment>>;
    #[wasm_bindgen(method, setter, slice_to_array)]
    pub fn set_attachments(this: &SendEmailBuilder, val: &[EmailAttachment]);
}
impl SendEmailBuilder {
    pub fn new<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        S3: ::wasm_bindgen::JsStringLike,
    >(
        from: S,
        to: S2,
        subject: S3,
    ) -> SendEmailBuilder {
        Self::builder(from, to, subject).build()
    }
    pub fn new_with_str_and_slice<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        from: S,
        to: &[String],
        subject: S2,
    ) -> SendEmailBuilder {
        Self::builder_with_str_and_slice(from, to, subject).build()
    }
    pub fn new_with_email_address_and_str<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        from: &EmailAddress,
        to: S,
        subject: S2,
    ) -> SendEmailBuilder {
        Self::builder_with_email_address_and_str(from, to, subject).build()
    }
    pub fn new_with_email_address_and_slice<S: ::wasm_bindgen::JsStringLike>(
        from: &EmailAddress,
        to: &[String],
        subject: S,
    ) -> SendEmailBuilder {
        Self::builder_with_email_address_and_slice(from, to, subject).build()
    }
    pub fn builder<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
        S3: ::wasm_bindgen::JsStringLike,
    >(
        from: S,
        to: S2,
        subject: S3,
    ) -> SendEmailBuilderBuilder {
        let inner: SendEmailBuilder = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_from(from);
        inner.set_to(to);
        inner.set_subject(subject);
        SendEmailBuilderBuilder { inner }
    }
    pub fn builder_with_str_and_slice<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        from: S,
        to: &[String],
        subject: S2,
    ) -> SendEmailBuilderBuilder {
        let inner: SendEmailBuilder = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_from(from);
        inner.set_to_with_slice(to);
        inner.set_subject(subject);
        SendEmailBuilderBuilder { inner }
    }
    pub fn builder_with_email_address_and_str<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        from: &EmailAddress,
        to: S,
        subject: S2,
    ) -> SendEmailBuilderBuilder {
        let inner: SendEmailBuilder = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_from_with_email_address(from);
        inner.set_to(to);
        inner.set_subject(subject);
        SendEmailBuilderBuilder { inner }
    }
    pub fn builder_with_email_address_and_slice<S: ::wasm_bindgen::JsStringLike>(
        from: &EmailAddress,
        to: &[String],
        subject: S,
    ) -> SendEmailBuilderBuilder {
        let inner: SendEmailBuilder = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_from_with_email_address(from);
        inner.set_to_with_slice(to);
        inner.set_subject(subject);
        SendEmailBuilderBuilder { inner }
    }
}
pub struct SendEmailBuilderBuilder {
    inner: SendEmailBuilder,
}
impl SendEmailBuilderBuilder {
    pub fn reply_to<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_reply_to(val);
        self
    }
    pub fn reply_to_with_email_address(self, val: &EmailAddress) -> Self {
        self.inner.set_reply_to_with_email_address(val);
        self
    }
    pub fn cc<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_cc(val);
        self
    }
    pub fn cc_with_slice(self, val: &[String]) -> Self {
        self.inner.set_cc_with_slice(val);
        self
    }
    pub fn bcc<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_bcc(val);
        self
    }
    pub fn bcc_with_slice(self, val: &[String]) -> Self {
        self.inner.set_bcc_with_slice(val);
        self
    }
    pub fn headers(self, val: &Object<JsString>) -> Self {
        self.inner.set_headers(val);
        self
    }
    pub fn text<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_text(val);
        self
    }
    pub fn html<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_html(val);
        self
    }
    pub fn attachments(self, val: &[EmailAttachment]) -> Self {
        self.inner.set_attachments(val);
        self
    }
    pub fn build(self) -> SendEmailBuilder {
        self.inner
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = ExtendableEvent , extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type EmailEvent;
    #[wasm_bindgen(method, getter)]
    pub fn message(this: &EmailEvent) -> ForwardableEmailMessage;
}
#[wasm_bindgen]
pub enum DispositionKind {
    Inline = "inline",
    Attachment = "attachment",
}
#[wasm_bindgen]
pub enum ContentKind {
    String(String),
    ArrayBuffer(ArrayBuffer),
    Uint8Array(Uint8Array),
}
#[wasm_bindgen]
pub enum FromKind {
    String(String),
    EmailAddress(EmailAddress),
}
#[wasm_bindgen]
pub enum ToKind {
    String(String),
    VecOfString(Vec<String>),
}
