// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[allow(dead_code)]
pub type FlagshipEvaluationContext = Object;
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type FlagshipEvaluationDetails<T: ::wasm_bindgen::JsGeneric>;
    #[wasm_bindgen(method, getter, js_name = "flagKey")]
    pub fn flag_key<T: ::wasm_bindgen::JsGeneric>(this: &FlagshipEvaluationDetails<T>) -> String;
    #[wasm_bindgen(method, setter, js_name = "flagKey")]
    pub fn set_flag_key<T: ::wasm_bindgen::JsGeneric>(
        this: &FlagshipEvaluationDetails<T>,
        val: &str,
    );
    #[wasm_bindgen(method, getter)]
    pub fn value<T: ::wasm_bindgen::JsGeneric>(this: &FlagshipEvaluationDetails<T>) -> T;
    #[wasm_bindgen(method, setter)]
    pub fn set_value<T: ::wasm_bindgen::JsGeneric>(this: &FlagshipEvaluationDetails<T>, val: &T);
    #[wasm_bindgen(method, getter)]
    pub fn variant<T: ::wasm_bindgen::JsGeneric>(
        this: &FlagshipEvaluationDetails<T>,
    ) -> Option<String>;
    #[wasm_bindgen(method, setter)]
    pub fn set_variant<T: ::wasm_bindgen::JsGeneric>(
        this: &FlagshipEvaluationDetails<T>,
        val: &str,
    );
    #[wasm_bindgen(method, getter)]
    pub fn reason<T: ::wasm_bindgen::JsGeneric>(
        this: &FlagshipEvaluationDetails<T>,
    ) -> Option<String>;
    #[wasm_bindgen(method, setter)]
    pub fn set_reason<T: ::wasm_bindgen::JsGeneric>(this: &FlagshipEvaluationDetails<T>, val: &str);
    #[wasm_bindgen(method, getter, js_name = "errorCode")]
    pub fn error_code<T: ::wasm_bindgen::JsGeneric>(
        this: &FlagshipEvaluationDetails<T>,
    ) -> Option<String>;
    #[wasm_bindgen(method, setter, js_name = "errorCode")]
    pub fn set_error_code<T: ::wasm_bindgen::JsGeneric>(
        this: &FlagshipEvaluationDetails<T>,
        val: &str,
    );
    #[wasm_bindgen(method, getter, js_name = "errorMessage")]
    pub fn error_message<T: ::wasm_bindgen::JsGeneric>(
        this: &FlagshipEvaluationDetails<T>,
    ) -> Option<String>;
    #[wasm_bindgen(method, setter, js_name = "errorMessage")]
    pub fn set_error_message<T: ::wasm_bindgen::JsGeneric>(
        this: &FlagshipEvaluationDetails<T>,
        val: &str,
    );
}
impl<T: ::wasm_bindgen::JsGeneric> FlagshipEvaluationDetails<T> {
    pub fn new(flag_key: &str, value: &T) -> FlagshipEvaluationDetails<T> {
        Self::builder(flag_key, value).build()
    }
    pub fn builder(flag_key: &str, value: &T) -> FlagshipEvaluationDetailsBuilder<T> {
        let inner: FlagshipEvaluationDetails<T> = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_flag_key(flag_key);
        inner.set_value(value);
        FlagshipEvaluationDetailsBuilder { inner }
    }
}
pub struct FlagshipEvaluationDetailsBuilder<T: ::wasm_bindgen::JsGeneric> {
    inner: FlagshipEvaluationDetails<T>,
}
impl<T: ::wasm_bindgen::JsGeneric> FlagshipEvaluationDetailsBuilder<T> {
    pub fn variant(self, val: &str) -> Self {
        self.inner.set_variant(val);
        self
    }
    pub fn reason(self, val: &str) -> Self {
        self.inner.set_reason(val);
        self
    }
    pub fn error_code(self, val: &str) -> Self {
        self.inner.set_error_code(val);
        self
    }
    pub fn error_message(self, val: &str) -> Self {
        self.inner.set_error_message(val);
        self
    }
    pub fn build(self) -> FlagshipEvaluationDetails<T> {
        self.inner
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Flagship;
    #[doc = " Get a flag value without type checking."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Optional default value returned when evaluation fails."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch)]
    pub async fn get(this: &Flagship, flag_key: &str) -> Result<JsValue, JsValue>;
    #[doc = " Get a flag value without type checking."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Optional default value returned when evaluation fails."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub async fn get_with_default_value(
        this: &Flagship,
        flag_key: &str,
        default_value: &JsValue,
    ) -> Result<JsValue, JsValue>;
    #[doc = " Get a flag value without type checking."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Optional default value returned when evaluation fails."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub async fn get_with_default_value_and_context(
        this: &Flagship,
        flag_key: &str,
        default_value: &JsValue,
        context: &Object,
    ) -> Result<JsValue, JsValue>;
    #[doc = " Get a boolean flag value."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Default value returned when evaluation fails or the flag type does not match."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "getBooleanValue")]
    pub async fn get_boolean_value(
        this: &Flagship,
        flag_key: &str,
        default_value: bool,
    ) -> Result<Boolean, JsValue>;
    #[doc = " Get a boolean flag value."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Default value returned when evaluation fails or the flag type does not match."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "getBooleanValue")]
    pub async fn get_boolean_value_with_context(
        this: &Flagship,
        flag_key: &str,
        default_value: bool,
        context: &Object,
    ) -> Result<Boolean, JsValue>;
    #[doc = " Get a boolean flag value with full evaluation details."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Default value returned when evaluation fails or the flag type does not match."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "getBooleanDetails")]
    pub async fn get_boolean_details(
        this: &Flagship,
        flag_key: &str,
        default_value: bool,
    ) -> Result<FlagshipEvaluationDetails<Boolean>, JsValue>;
    #[doc = " Get a boolean flag value with full evaluation details."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Default value returned when evaluation fails or the flag type does not match."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "getBooleanDetails")]
    pub async fn get_boolean_details_with_context(
        this: &Flagship,
        flag_key: &str,
        default_value: bool,
        context: &Object,
    ) -> Result<FlagshipEvaluationDetails<Boolean>, JsValue>;
}
