// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[allow(dead_code)]
pub type FlagshipEvaluationContext = Object;
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type FlagshipEvaluationDetails<T>;
    #[wasm_bindgen(method, getter, js_name = "flagKey")]
    pub fn flag_key<T>(this: &FlagshipEvaluationDetails<T>) -> String;
    #[wasm_bindgen(method, getter, js_name = "flagKey")]
    pub fn flag_key_js_string<T>(this: &FlagshipEvaluationDetails<T>) -> JsString;
    #[wasm_bindgen(method, setter, js_name = "flagKey")]
    pub fn set_flag_key<T, S: ::wasm_bindgen::JsStringLike>(
        this: &FlagshipEvaluationDetails<T>,
        val: S,
    );
    #[wasm_bindgen(method, getter)]
    pub fn value<T>(this: &FlagshipEvaluationDetails<T>) -> T;
    #[wasm_bindgen(method, setter)]
    pub fn set_value<T>(this: &FlagshipEvaluationDetails<T>, val: T);
    #[wasm_bindgen(method, getter)]
    pub fn variant<T>(this: &FlagshipEvaluationDetails<T>) -> Option<String>;
    #[wasm_bindgen(method, getter, js_name = "variant")]
    pub fn variant_js_string<T>(this: &FlagshipEvaluationDetails<T>) -> Option<JsString>;
    #[wasm_bindgen(method, setter)]
    pub fn set_variant<T, S: ::wasm_bindgen::JsStringLike>(
        this: &FlagshipEvaluationDetails<T>,
        val: S,
    );
    #[wasm_bindgen(method, getter)]
    pub fn reason<T>(this: &FlagshipEvaluationDetails<T>) -> Option<String>;
    #[wasm_bindgen(method, getter, js_name = "reason")]
    pub fn reason_js_string<T>(this: &FlagshipEvaluationDetails<T>) -> Option<JsString>;
    #[wasm_bindgen(method, setter)]
    pub fn set_reason<T, S: ::wasm_bindgen::JsStringLike>(
        this: &FlagshipEvaluationDetails<T>,
        val: S,
    );
    #[wasm_bindgen(method, getter, js_name = "errorCode")]
    pub fn error_code<T>(this: &FlagshipEvaluationDetails<T>) -> Option<String>;
    #[wasm_bindgen(method, getter, js_name = "errorCode")]
    pub fn error_code_js_string<T>(this: &FlagshipEvaluationDetails<T>) -> Option<JsString>;
    #[wasm_bindgen(method, setter, js_name = "errorCode")]
    pub fn set_error_code<T, S: ::wasm_bindgen::JsStringLike>(
        this: &FlagshipEvaluationDetails<T>,
        val: S,
    );
    #[wasm_bindgen(method, getter, js_name = "errorMessage")]
    pub fn error_message<T>(this: &FlagshipEvaluationDetails<T>) -> Option<String>;
    #[wasm_bindgen(method, getter, js_name = "errorMessage")]
    pub fn error_message_js_string<T>(this: &FlagshipEvaluationDetails<T>) -> Option<JsString>;
    #[wasm_bindgen(method, setter, js_name = "errorMessage")]
    pub fn set_error_message<T, S: ::wasm_bindgen::JsStringLike>(
        this: &FlagshipEvaluationDetails<T>,
        val: S,
    );
}
impl<T: ::wasm_bindgen::convert::IntoWasmAbi> FlagshipEvaluationDetails<T> {
    pub fn new<S: ::wasm_bindgen::JsStringLike>(
        flag_key: S,
        value: T,
    ) -> FlagshipEvaluationDetails<T> {
        Self::builder(flag_key, value).build()
    }
    pub fn builder<S: ::wasm_bindgen::JsStringLike>(
        flag_key: S,
        value: T,
    ) -> FlagshipEvaluationDetailsBuilder<T> {
        let inner: FlagshipEvaluationDetails<T> = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_flag_key(flag_key);
        inner.set_value(value);
        FlagshipEvaluationDetailsBuilder { inner }
    }
}
pub struct FlagshipEvaluationDetailsBuilder<T: ::wasm_bindgen::convert::IntoWasmAbi> {
    inner: FlagshipEvaluationDetails<T>,
}
impl<T: ::wasm_bindgen::convert::IntoWasmAbi> FlagshipEvaluationDetailsBuilder<T> {
    pub fn variant<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_variant(val);
        self
    }
    pub fn reason<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_reason(val);
        self
    }
    pub fn error_code<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_error_code(val);
        self
    }
    pub fn error_message<S: ::wasm_bindgen::JsStringLike>(self, val: S) -> Self {
        self.inner.set_error_message(val);
        self
    }
    pub fn build(self) -> FlagshipEvaluationDetails<T> {
        self.inner
    }
}
#[wasm_bindgen(experimental_generic_mono)]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Flagship;
    #[doc = " Get a flag value without type checking."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Optional default value returned when evaluation fails."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch)]
    pub async fn get<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
    ) -> Result<JsValue, JsValue>;
    #[doc = " Get a flag value without type checking."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Optional default value returned when evaluation fails."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub async fn get_with_default_value<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: &JsValue,
    ) -> Result<JsValue, JsValue>;
    #[doc = " Get a flag value without type checking."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Optional default value returned when evaluation fails."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "get")]
    pub async fn get_with_default_value_and_context<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: &JsValue,
        context: &Object,
    ) -> Result<JsValue, JsValue>;
    #[doc = " Get a boolean flag value."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Default value returned when evaluation fails or the flag type does not match."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "getBooleanValue")]
    pub async fn get_boolean_value<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: bool,
    ) -> Result<bool, JsValue>;
    #[doc = " Get a boolean flag value."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Default value returned when evaluation fails or the flag type does not match."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "getBooleanValue")]
    pub async fn get_boolean_value_with_context<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: bool,
        context: &Object,
    ) -> Result<bool, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringValue")]
    pub async fn get_string_value<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        this: &Flagship,
        flag_key: S,
        default_value: S2,
    ) -> Result<String, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringValue")]
    pub async fn get_string_value_js_string<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        this: &Flagship,
        flag_key: S,
        default_value: S2,
    ) -> Result<JsString, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringValue")]
    pub async fn get_string_value_with_context<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        this: &Flagship,
        flag_key: S,
        default_value: S2,
        context: &Object,
    ) -> Result<String, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringValue")]
    pub async fn get_string_value_with_context_js_string<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        this: &Flagship,
        flag_key: S,
        default_value: S2,
        context: &Object,
    ) -> Result<JsString, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getNumberValue")]
    pub async fn get_number_value<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: f64,
    ) -> Result<f64, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getNumberValue")]
    pub async fn get_number_value_with_context<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: f64,
        context: &Object,
    ) -> Result<f64, JsValue>;
    #[doc = " Get a boolean flag value with full evaluation details."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Default value returned when evaluation fails or the flag type does not match."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "getBooleanDetails")]
    pub async fn get_boolean_details<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: bool,
    ) -> Result<FlagshipEvaluationDetails<bool>, JsValue>;
    #[doc = " Get a boolean flag value with full evaluation details."]
    #[doc = ""]
    #[doc = " * `flagKey` - The key of the flag to evaluate."]
    #[doc = " * `defaultValue` - Default value returned when evaluation fails or the flag type does not match."]
    #[doc = " * `context` - Optional evaluation context for targeting rules."]
    #[wasm_bindgen(method, catch, js_name = "getBooleanDetails")]
    pub async fn get_boolean_details_with_context<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: bool,
        context: &Object,
    ) -> Result<FlagshipEvaluationDetails<bool>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringDetails")]
    pub async fn get_string_details<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        this: &Flagship,
        flag_key: S,
        default_value: S2,
    ) -> Result<FlagshipEvaluationDetails<String>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringDetails")]
    pub async fn get_string_details_js_string<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        this: &Flagship,
        flag_key: S,
        default_value: S2,
    ) -> Result<FlagshipEvaluationDetails<JsString>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringDetails")]
    pub async fn get_string_details_with_context<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        this: &Flagship,
        flag_key: S,
        default_value: S2,
        context: &Object,
    ) -> Result<FlagshipEvaluationDetails<String>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getStringDetails")]
    pub async fn get_string_details_with_context_js_string<
        S: ::wasm_bindgen::JsStringLike,
        S2: ::wasm_bindgen::JsStringLike,
    >(
        this: &Flagship,
        flag_key: S,
        default_value: S2,
        context: &Object,
    ) -> Result<FlagshipEvaluationDetails<JsString>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getNumberDetails")]
    pub async fn get_number_details<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: f64,
    ) -> Result<FlagshipEvaluationDetails<f64>, JsValue>;
    #[wasm_bindgen(method, catch, js_name = "getNumberDetails")]
    pub async fn get_number_details_with_context<S: ::wasm_bindgen::JsStringLike>(
        this: &Flagship,
        flag_key: S,
        default_value: f64,
        context: &Object,
    ) -> Result<FlagshipEvaluationDetails<f64>, JsValue>;
}
