// Generated by ts-gen. Do not edit.

#[allow(unused_imports)]
use js_sys::*;
#[allow(unused_imports)]
use wasm_bindgen::prelude::*;
#[allow(dead_code)]
pub type VectorizeVectorMetadataValue = JsValue;
#[allow(dead_code)]
pub type VectorizeVectorMetadata = JsValue;
#[allow(dead_code)]
pub type VectorFloatArray = JsValue;
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VectorizeVectorMetadataFilterOp {
    Eq = "$eq",
    Ne = "$ne",
    Lt = "$lt",
    Lte = "$lte",
    Gt = "$gt",
    Gte = "$gte",
}
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VectorizeVectorMetadataFilterCollectionOp {
    In = "$in",
    Nin = "$nin",
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type VectorizeVectorMetadataFilter;
}
#[wasm_bindgen]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum VectorizeMetadataRetrievalLevel {
    All = "all",
    Indexed = "indexed",
    None = "none",
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type VectorizeQueryOptions;
    #[wasm_bindgen(method, getter, js_name = "topK")]
    pub fn top_k(this: &VectorizeQueryOptions) -> Option<f64>;
    #[wasm_bindgen(method, setter, js_name = "topK")]
    pub fn set_top_k(this: &VectorizeQueryOptions, val: f64);
    #[wasm_bindgen(method, getter)]
    pub fn namespace(this: &VectorizeQueryOptions) -> Option<String>;
    #[wasm_bindgen(method, setter)]
    pub fn set_namespace(this: &VectorizeQueryOptions, val: &str);
    #[wasm_bindgen(method, getter, js_name = "returnValues")]
    pub fn return_values(this: &VectorizeQueryOptions) -> Option<bool>;
    #[wasm_bindgen(method, setter, js_name = "returnValues")]
    pub fn set_return_values(this: &VectorizeQueryOptions, val: bool);
    #[wasm_bindgen(method, getter, js_name = "returnMetadata")]
    pub fn return_metadata(this: &VectorizeQueryOptions) -> Option<ReturnMetadataKind>;
    #[wasm_bindgen(method, setter, js_name = "returnMetadata")]
    pub fn set_return_metadata(this: &VectorizeQueryOptions, val: bool);
    #[wasm_bindgen(method, setter, js_name = "returnMetadata")]
    pub fn set_return_metadata_with_vectorize_metadata_retrieval_level(
        this: &VectorizeQueryOptions,
        val: VectorizeMetadataRetrievalLevel,
    );
    #[wasm_bindgen(method, getter)]
    pub fn filter(this: &VectorizeQueryOptions) -> Option<VectorizeVectorMetadataFilter>;
    #[wasm_bindgen(method, setter)]
    pub fn set_filter(this: &VectorizeQueryOptions, val: &VectorizeVectorMetadataFilter);
}
impl VectorizeQueryOptions {
    pub fn new() -> VectorizeQueryOptions {
        Self::builder().build()
    }
    pub fn builder() -> VectorizeQueryOptionsBuilder {
        VectorizeQueryOptionsBuilder {
            inner: JsCast::unchecked_into(js_sys::Object::new()),
        }
    }
}
pub struct VectorizeQueryOptionsBuilder {
    inner: VectorizeQueryOptions,
}
impl VectorizeQueryOptionsBuilder {
    pub fn top_k(self, val: f64) -> Self {
        self.inner.set_top_k(val);
        self
    }
    pub fn namespace(self, val: &str) -> Self {
        self.inner.set_namespace(val);
        self
    }
    pub fn return_values(self, val: bool) -> Self {
        self.inner.set_return_values(val);
        self
    }
    pub fn return_metadata(self, val: bool) -> Self {
        self.inner.set_return_metadata(val);
        self
    }
    pub fn return_metadata_with_vectorize_metadata_retrieval_level(
        self,
        val: VectorizeMetadataRetrievalLevel,
    ) -> Self {
        self.inner
            .set_return_metadata_with_vectorize_metadata_retrieval_level(val);
        self
    }
    pub fn filter(self, val: &VectorizeVectorMetadataFilter) -> Self {
        self.inner.set_filter(val);
        self
    }
    pub fn build(self) -> VectorizeQueryOptions {
        self.inner
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type VectorizeIndexInfo;
    #[doc = " The number of records containing vectors within the index."]
    #[wasm_bindgen(method, getter, js_name = "vectorCount")]
    pub fn vector_count(this: &VectorizeIndexInfo) -> f64;
    #[wasm_bindgen(method, setter, js_name = "vectorCount")]
    pub fn set_vector_count(this: &VectorizeIndexInfo, val: f64);
    #[doc = " Number of dimensions the index has been configured for."]
    #[wasm_bindgen(method, getter)]
    pub fn dimensions(this: &VectorizeIndexInfo) -> f64;
    #[wasm_bindgen(method, setter)]
    pub fn set_dimensions(this: &VectorizeIndexInfo, val: f64);
    #[doc = " ISO 8601 datetime of the last processed mutation on in the index. All changes before this mutation will be reflected in the index state."]
    #[wasm_bindgen(method, getter, js_name = "processedUpToDatetime")]
    pub fn processed_up_to_datetime(this: &VectorizeIndexInfo) -> f64;
    #[wasm_bindgen(method, setter, js_name = "processedUpToDatetime")]
    pub fn set_processed_up_to_datetime(this: &VectorizeIndexInfo, val: f64);
    #[doc = " UUIDv4 of the last mutation processed by the index. All changes before this mutation will be reflected in the index state."]
    #[wasm_bindgen(method, getter, js_name = "processedUpToMutation")]
    pub fn processed_up_to_mutation(this: &VectorizeIndexInfo) -> f64;
    #[wasm_bindgen(method, setter, js_name = "processedUpToMutation")]
    pub fn set_processed_up_to_mutation(this: &VectorizeIndexInfo, val: f64);
}
impl VectorizeIndexInfo {
    #[doc = " * `vector_count` - The number of records containing vectors within the index."]
    #[doc = " * `dimensions` - Number of dimensions the index has been configured for."]
    #[doc = " * `processed_up_to_datetime` - ISO 8601 datetime of the last processed mutation on in the index. All changes before this mutation will be reflected in the index state."]
    #[doc = " * `processed_up_to_mutation` - UUIDv4 of the last mutation processed by the index. All changes before this mutation will be reflected in the index state."]
    pub fn new(
        vector_count: f64,
        dimensions: f64,
        processed_up_to_datetime: f64,
        processed_up_to_mutation: f64,
    ) -> VectorizeIndexInfo {
        let inner: VectorizeIndexInfo = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_vector_count(vector_count);
        inner.set_dimensions(dimensions);
        inner.set_processed_up_to_datetime(processed_up_to_datetime);
        inner.set_processed_up_to_mutation(processed_up_to_mutation);
        inner
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type VectorizeVector;
    #[doc = " The ID for the vector. This can be user-defined, and must be unique. It should uniquely identify the object, and is best set based on the ID of what the vector represents."]
    #[wasm_bindgen(method, getter)]
    pub fn id(this: &VectorizeVector) -> String;
    #[wasm_bindgen(method, setter)]
    pub fn set_id(this: &VectorizeVector, val: &str);
    #[doc = " The vector values"]
    #[wasm_bindgen(method, getter)]
    pub fn values(this: &VectorizeVector) -> ValuesKind;
    #[wasm_bindgen(method, setter)]
    pub fn set_values(this: &VectorizeVector, val: &Float32Array);
    #[wasm_bindgen(method, setter, js_name = "values")]
    pub fn set_values_with_float64_array(this: &VectorizeVector, val: &Float64Array);
    #[wasm_bindgen(method, setter, js_name = "values")]
    pub fn set_values_with_slice(this: &VectorizeVector, val: &[f64]);
    #[doc = " The namespace this vector belongs to."]
    #[wasm_bindgen(method, getter)]
    pub fn namespace(this: &VectorizeVector) -> Option<String>;
    #[wasm_bindgen(method, setter)]
    pub fn set_namespace(this: &VectorizeVector, val: &str);
    #[doc = " Metadata associated with the vector. Includes the values of other fields and potentially additional details."]
    #[wasm_bindgen(method, getter)]
    pub fn metadata(this: &VectorizeVector) -> Option<Object>;
    #[wasm_bindgen(method, setter)]
    pub fn set_metadata(this: &VectorizeVector, val: &Object);
}
impl VectorizeVector {
    #[doc = " * `id` - The ID for the vector. This can be user-defined, and must be unique. It should uniquely identify the object, and is best set based on the ID of what the vector represents."]
    #[doc = " * `values` - The vector values"]
    pub fn new(id: &str, values: &Float32Array) -> VectorizeVector {
        Self::builder(id, values).build()
    }
    #[doc = " * `id` - The ID for the vector. This can be user-defined, and must be unique. It should uniquely identify the object, and is best set based on the ID of what the vector represents."]
    #[doc = " * `values` - The vector values"]
    pub fn new_with_float64_array(id: &str, values: &Float64Array) -> VectorizeVector {
        Self::builder_with_float64_array(id, values).build()
    }
    #[doc = " * `id` - The ID for the vector. This can be user-defined, and must be unique. It should uniquely identify the object, and is best set based on the ID of what the vector represents."]
    #[doc = " * `values` - The vector values"]
    pub fn new_with_slice(id: &str, values: &[f64]) -> VectorizeVector {
        Self::builder_with_slice(id, values).build()
    }
    #[doc = " * `id` - The ID for the vector. This can be user-defined, and must be unique. It should uniquely identify the object, and is best set based on the ID of what the vector represents."]
    #[doc = " * `values` - The vector values"]
    pub fn builder(id: &str, values: &Float32Array) -> VectorizeVectorBuilder {
        let inner: VectorizeVector = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_id(id);
        inner.set_values(values);
        VectorizeVectorBuilder { inner }
    }
    #[doc = " * `id` - The ID for the vector. This can be user-defined, and must be unique. It should uniquely identify the object, and is best set based on the ID of what the vector represents."]
    #[doc = " * `values` - The vector values"]
    pub fn builder_with_float64_array(id: &str, values: &Float64Array) -> VectorizeVectorBuilder {
        let inner: VectorizeVector = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_id(id);
        inner.set_values_with_float64_array(values);
        VectorizeVectorBuilder { inner }
    }
    #[doc = " * `id` - The ID for the vector. This can be user-defined, and must be unique. It should uniquely identify the object, and is best set based on the ID of what the vector represents."]
    #[doc = " * `values` - The vector values"]
    pub fn builder_with_slice(id: &str, values: &[f64]) -> VectorizeVectorBuilder {
        let inner: VectorizeVector = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_id(id);
        inner.set_values_with_slice(values);
        VectorizeVectorBuilder { inner }
    }
}
pub struct VectorizeVectorBuilder {
    inner: VectorizeVector,
}
impl VectorizeVectorBuilder {
    pub fn namespace(self, val: &str) -> Self {
        self.inner.set_namespace(val);
        self
    }
    pub fn metadata(self, val: &Object) -> Self {
        self.inner.set_metadata(val);
        self
    }
    pub fn build(self) -> VectorizeVector {
        self.inner
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type VectorizeMatch;
    #[doc = " The ID for the vector."]
    #[wasm_bindgen(method, getter)]
    pub fn id(this: &VectorizeMatch) -> String;
    #[wasm_bindgen(method, setter)]
    pub fn set_id(this: &VectorizeMatch, val: &str);
    #[doc = " The vector values, when `returnValues` was requested."]
    #[wasm_bindgen(method, getter)]
    pub fn values(this: &VectorizeMatch) -> Option<ValuesKind>;
    #[wasm_bindgen(method, setter)]
    pub fn set_values(this: &VectorizeMatch, val: &Float32Array);
    #[wasm_bindgen(method, setter, js_name = "values")]
    pub fn set_values_with_float64_array(this: &VectorizeMatch, val: &Float64Array);
    #[wasm_bindgen(method, setter, js_name = "values")]
    pub fn set_values_with_slice(this: &VectorizeMatch, val: &[f64]);
    #[doc = " The namespace this vector belongs to."]
    #[wasm_bindgen(method, getter)]
    pub fn namespace(this: &VectorizeMatch) -> Option<String>;
    #[wasm_bindgen(method, setter)]
    pub fn set_namespace(this: &VectorizeMatch, val: &str);
    #[doc = " Metadata associated with the vector, when `returnMetadata` was requested."]
    #[wasm_bindgen(method, getter)]
    pub fn metadata(this: &VectorizeMatch) -> Option<Object>;
    #[wasm_bindgen(method, setter)]
    pub fn set_metadata(this: &VectorizeMatch, val: &Object);
    #[doc = " The score or rank for similarity, when returned as a result"]
    #[wasm_bindgen(method, getter)]
    pub fn score(this: &VectorizeMatch) -> f64;
    #[wasm_bindgen(method, setter)]
    pub fn set_score(this: &VectorizeMatch, val: f64);
}
impl VectorizeMatch {
    #[doc = " * `id` - The ID for the vector."]
    #[doc = " * `score` - The score or rank for similarity, when returned as a result"]
    pub fn new(id: &str, score: f64) -> VectorizeMatch {
        Self::builder(id, score).build()
    }
    #[doc = " * `id` - The ID for the vector."]
    #[doc = " * `score` - The score or rank for similarity, when returned as a result"]
    pub fn builder(id: &str, score: f64) -> VectorizeMatchBuilder {
        let inner: VectorizeMatch = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_id(id);
        inner.set_score(score);
        VectorizeMatchBuilder { inner }
    }
}
pub struct VectorizeMatchBuilder {
    inner: VectorizeMatch,
}
impl VectorizeMatchBuilder {
    pub fn values(self, val: &Float32Array) -> Self {
        self.inner.set_values(val);
        self
    }
    pub fn values_with_float64_array(self, val: &Float64Array) -> Self {
        self.inner.set_values_with_float64_array(val);
        self
    }
    pub fn values_with_slice(self, val: &[f64]) -> Self {
        self.inner.set_values_with_slice(val);
        self
    }
    pub fn namespace(self, val: &str) -> Self {
        self.inner.set_namespace(val);
        self
    }
    pub fn metadata(self, val: &Object) -> Self {
        self.inner.set_metadata(val);
        self
    }
    pub fn build(self) -> VectorizeMatch {
        self.inner
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type VectorizeMatches;
    #[wasm_bindgen(method, getter)]
    pub fn matches(this: &VectorizeMatches) -> Vec<VectorizeMatch>;
    #[wasm_bindgen(method, setter, slice_to_array)]
    pub fn set_matches(this: &VectorizeMatches, val: &[VectorizeMatch]);
    #[wasm_bindgen(method, getter)]
    pub fn count(this: &VectorizeMatches) -> f64;
    #[wasm_bindgen(method, setter)]
    pub fn set_count(this: &VectorizeMatches, val: f64);
}
impl VectorizeMatches {
    pub fn new(matches: &[VectorizeMatch], count: f64) -> VectorizeMatches {
        let inner: VectorizeMatches = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_matches(matches);
        inner.set_count(count);
        inner
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type VectorizeAsyncMutation;
    #[doc = " The unique identifier for the async mutation operation containing the changeset."]
    #[wasm_bindgen(method, getter, js_name = "mutationId")]
    pub fn mutation_id(this: &VectorizeAsyncMutation) -> String;
    #[wasm_bindgen(method, setter, js_name = "mutationId")]
    pub fn set_mutation_id(this: &VectorizeAsyncMutation, val: &str);
}
impl VectorizeAsyncMutation {
    #[doc = " * `mutation_id` - The unique identifier for the async mutation operation containing the changeset."]
    pub fn new(mutation_id: &str) -> VectorizeAsyncMutation {
        let inner: VectorizeAsyncMutation = JsCast::unchecked_into(js_sys::Object::new());
        inner.set_mutation_id(mutation_id);
        inner
    }
}
#[wasm_bindgen]
extern "C" {
    # [wasm_bindgen (extends = Object)]
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub type Vectorize;
    #[doc = " Get information about the currently bound index."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with information about the current index."]
    #[wasm_bindgen(method, catch)]
    pub async fn describe(this: &Vectorize) -> Result<VectorizeIndexInfo, Error>;
    #[doc = " Use the provided vector to perform a similarity search across the index."]
    #[doc = ""]
    #[doc = " * `vector` - Input vector that will be used to drive the similarity search."]
    #[doc = " * `options` - Configuration options to massage the returned data."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with matched and scored vectors."]
    #[wasm_bindgen(method, catch)]
    pub async fn query(this: &Vectorize, vector: &Float32Array) -> Result<VectorizeMatches, Error>;
    #[doc = " Use the provided vector to perform a similarity search across the index."]
    #[doc = ""]
    #[doc = " * `vector` - Input vector that will be used to drive the similarity search."]
    #[doc = " * `options` - Configuration options to massage the returned data."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with matched and scored vectors."]
    #[wasm_bindgen(method, catch, js_name = "query")]
    pub async fn query_with_float64_array(
        this: &Vectorize,
        vector: &Float64Array,
    ) -> Result<VectorizeMatches, Error>;
    #[doc = " Use the provided vector to perform a similarity search across the index."]
    #[doc = ""]
    #[doc = " * `vector` - Input vector that will be used to drive the similarity search."]
    #[doc = " * `options` - Configuration options to massage the returned data."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with matched and scored vectors."]
    #[wasm_bindgen(method, catch, js_name = "query")]
    pub async fn query_with_slice(
        this: &Vectorize,
        vector: &[f64],
    ) -> Result<VectorizeMatches, Error>;
    #[doc = " Use the provided vector to perform a similarity search across the index."]
    #[doc = ""]
    #[doc = " * `vector` - Input vector that will be used to drive the similarity search."]
    #[doc = " * `options` - Configuration options to massage the returned data."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with matched and scored vectors."]
    #[wasm_bindgen(method, catch, js_name = "query")]
    pub async fn query_with_float32_array_and_options(
        this: &Vectorize,
        vector: &Float32Array,
        options: &VectorizeQueryOptions,
    ) -> Result<VectorizeMatches, Error>;
    #[doc = " Use the provided vector to perform a similarity search across the index."]
    #[doc = ""]
    #[doc = " * `vector` - Input vector that will be used to drive the similarity search."]
    #[doc = " * `options` - Configuration options to massage the returned data."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with matched and scored vectors."]
    #[wasm_bindgen(method, catch, js_name = "query")]
    pub async fn query_with_float64_array_and_options(
        this: &Vectorize,
        vector: &Float64Array,
        options: &VectorizeQueryOptions,
    ) -> Result<VectorizeMatches, Error>;
    #[doc = " Use the provided vector to perform a similarity search across the index."]
    #[doc = ""]
    #[doc = " * `vector` - Input vector that will be used to drive the similarity search."]
    #[doc = " * `options` - Configuration options to massage the returned data."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with matched and scored vectors."]
    #[wasm_bindgen(method, catch, js_name = "query")]
    pub async fn query_with_slice_and_options(
        this: &Vectorize,
        vector: &[f64],
        options: &VectorizeQueryOptions,
    ) -> Result<VectorizeMatches, Error>;
    #[doc = " Use the provided vector-id to perform a similarity search across the index."]
    #[doc = ""]
    #[doc = " * `vectorId` - Id for a vector in the index against which the index should be queried."]
    #[doc = " * `options` - Configuration options to massage the returned data."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with matched and scored vectors."]
    #[wasm_bindgen(method, catch, js_name = "queryById")]
    pub async fn query_by_id(this: &Vectorize, vector_id: &str) -> Result<VectorizeMatches, Error>;
    #[doc = " Use the provided vector-id to perform a similarity search across the index."]
    #[doc = ""]
    #[doc = " * `vectorId` - Id for a vector in the index against which the index should be queried."]
    #[doc = " * `options` - Configuration options to massage the returned data."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with matched and scored vectors."]
    #[wasm_bindgen(method, catch, js_name = "queryById")]
    pub async fn query_by_id_with_options(
        this: &Vectorize,
        vector_id: &str,
        options: &VectorizeQueryOptions,
    ) -> Result<VectorizeMatches, Error>;
    #[doc = " Insert a list of vectors into the index dataset. If a provided id exists, an error will be thrown."]
    #[doc = ""]
    #[doc = " * `vectors` - List of vectors that will be inserted."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with a unique identifier of a mutation containing the insert changeset."]
    #[wasm_bindgen(method, catch, slice_to_array)]
    pub async fn insert(
        this: &Vectorize,
        vectors: &[VectorizeVector],
    ) -> Result<VectorizeAsyncMutation, Error>;
    #[doc = " Upsert a list of vectors into the index dataset. If a provided id exists, it will be replaced with the new values."]
    #[doc = ""]
    #[doc = " * `vectors` - List of vectors that will be upserted."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with a unique identifier of a mutation containing the upsert changeset."]
    #[wasm_bindgen(method, catch, slice_to_array)]
    pub async fn upsert(
        this: &Vectorize,
        vectors: &[VectorizeVector],
    ) -> Result<VectorizeAsyncMutation, Error>;
    #[doc = " Delete a list of vectors with a matching id."]
    #[doc = ""]
    #[doc = " * `ids` - List of vector ids that should be deleted."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with a unique identifier of a mutation containing the delete changeset."]
    #[wasm_bindgen(method, catch, slice_to_array, js_name = "deleteByIds")]
    pub async fn delete_by_ids(
        this: &Vectorize,
        ids: &[String],
    ) -> Result<VectorizeAsyncMutation, Error>;
    #[doc = " Get a list of vectors with a matching id."]
    #[doc = ""]
    #[doc = " * `ids` - List of vector ids that should be returned."]
    #[doc = ""]
    #[doc = " Returns: A promise that resolves with the raw unscored vectors matching the id set."]
    #[wasm_bindgen(method, catch, slice_to_array, js_name = "getByIds")]
    pub async fn get_by_ids(
        this: &Vectorize,
        ids: &[String],
    ) -> Result<Array<VectorizeVector>, Error>;
}
#[wasm_bindgen]
pub enum ReturnMetadataKind {
    Bool(bool),
    JsString(JsString),
}
#[wasm_bindgen]
pub enum ValuesKind {
    VectorFloatArray(JsValue),
    VecOfF64(Vec<f64>),
}
