use js_sys::{Function, Object, Reflect};
use serde::Serialize;
use wasm_bindgen::{JsCast, JsValue};

use crate::{Error, Result};

/// A Rust wrapper for the loopback bindings in [`ctx.exports`](https://developers.cloudflare.com/workers/runtime-apis/context/#exports).
/// These bindings refer to Worker entrypoints and configured Durable Object namespaces in the same Worker and are provided automatically from its top-level exports.
///
/// Obtain this wrapper through [`crate::Context::exports`], [`crate::State::exports`], or [`crate::ScheduleContext::exports`].
/// In TypeScript, bindings are accessed as properties of `ctx.exports`; this wrapper provides [`Self::get`] and [`Self::get_with_props`] instead.
#[derive(Debug, Clone)]
pub struct Exports {
    inner: JsValue,
}

impl Exports {
    pub(crate) fn new(inner: JsValue) -> Result<Self> {
        if !inner.is_object() {
            return Err(Error::RustError(
                "ctx.exports is unavailable; enable the enable_ctx_exports compatibility flag"
                    .into(),
            ));
        }
        Ok(Self { inner })
    }

    /// Gets a loopback binding by its export name.
    ///
    /// Corresponds to `ctx.exports[name]` in TypeScript. The caller is responsible for converting the returned JavaScript value to the appropriate binding type.
    /// Use `"default"` for the entrypoint generated by `#[event(fetch)]`.
    ///
    /// # Errors
    ///
    /// Returns an error if the export is missing or its property cannot be read.
    pub fn get(&self, name: &str) -> Result<JsValue> {
        let binding = Reflect::get(&self.inner, &JsValue::from_str(name))?;
        if binding.is_null() || binding.is_undefined() {
            return Err(Error::RustError(format!(
                "Worker export {name:?} was not found"
            )));
        }
        Ok(binding)
    }

    /// Calls a loopback binding factory with the specified props.
    ///
    /// Corresponds to `ctx.exports[name]({ props })` in TypeScript. The returned JavaScript value is not checked or converted to a specific binding type.
    /// For a service binding, the callee reads the props using [`crate::Context::props`] on each call through the returned binding.
    ///
    /// A supplied props must be a JavaScript object, such as a serialized struct, map, or sequence.
    /// Scalar strings, numbers, and booleans are rejected by the runtime.
    ///
    /// This example assumes `OutboundProxy` is a service binding.
    ///
    /// ```no_run
    /// # use serde::Serialize;
    /// # use worker::{wasm_bindgen::JsCast, Context, Fetcher, Result};
    /// # fn example(ctx: &Context) -> Result<()> {
    /// #[derive(Serialize)]
    /// struct Props {
    ///     container_id: String,
    /// }
    ///
    /// let binding = ctx.exports().get_with_props(
    ///     "OutboundProxy",
    ///     &Props { container_id: "my-container".into() },
    /// )?;
    /// let handler = Fetcher::unchecked_from_js(binding);
    /// # Ok(())
    /// # }
    /// ```
    ///
    /// # Errors
    ///
    /// Returns an error if the export is missing, cannot be read, or is not callable, props cannot be serialized, or the factory call throws an exception.
    pub fn get_with_props<T: Serialize>(&self, name: &str, props: &T) -> Result<JsValue> {
        let factory = self.get(name)?.dyn_into::<Function>().map_err(|_| {
            Error::RustError(format!(
                "Worker export {name:?} is not a loopback binding factory"
            ))
        })?;
        let options = Object::new();
        Reflect::set(
            &options,
            &"props".into(),
            &serde_wasm_bindgen::to_value(props)?,
        )?;
        let arguments = js_sys::Array::of1(&options);
        Ok(Reflect::apply(&factory, &JsValue::UNDEFINED, &arguments)?)
    }
}
