[package]
name = "queue-on-workers"
version = "0.1.0"
edition = "2021"

[package.metadata.release]
release = false

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
worker = { workspace = true, features = ["queue"] }
js-sys.workspace = true
