name = "sync-kv-example"
main = "build/index.js"
compatibility_date = "2025-09-23"

[build]
command = "cargo install \"worker-build@^0.8\" && worker-build --release"

[[durable_objects.bindings]]
name = "SYNC_KV"
class_name = "SyncKvDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncKvDurableObject"]
