# For God so loved the world, that He gave His only begotten Son, that all who believe in Him should not perish but have everlasting life
[template]
ignore = [ 
  "assets/favicon.ico",
  "public/favicon.ico"
]
