{% if win -%}
  {% assign prefix = "$env:" -%}
  {% assign suffix = "&&" -%}
{% endif -%}
name = "{{project-name}}"
main = "build/index.js"
compatibility_date = "{{ "now" | date: "%Y-%m-%d" }}"

[build]
command = "cargo leptos build --release && cargo install -q \"worker-build@^0.7\" && {{prefix}}LEPTOS_OUTPUT_NAME={{project-name}}{{suffix}} worker-build --release --features ssr"

[assets]
directory = "./target/site"
